FROM python:3.6-slim

ENV AIRFLOW_HOME=/airflow

COPY resources/data /data
COPY resources/airflow/requirements.txt /resources/airflow/requirements.txt
COPY resources/airflow/constraints.txt /resources/airflow/constraints.txt
RUN pip install -r resources/airflow/requirements.txt -c resources/airflow/constraints.txt
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

RUN mkdir -p $AIRFLOW_HOME/dags $AIRFLOW_HOME/logs $AIRFLOW_HOME/plugins

COPY resources/airflow/setup.py $AIRFLOW_HOME/dags

COPY resources/airflow/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

COPY resources/train_spark_mllib_model.py /resources/train_spark_mllib_model.py

RUN apt-get update && apt-get install -y openjdk-11-jdk procps


ENV SPARK_VERSION=3.5.1
ENV HADOOP_VERSION=3
ENV SPARK_HOME=/opt/spark
ENV PATH="${SPARK_HOME}/bin:${PATH}"

RUN apt-get update && apt-get install -y supervisor && apt-get install -y curl \
    && curl -L https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz \
    | tar -xz -C /opt && \
    mv /opt/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION} ${SPARK_HOME}

EXPOSE 8180

CMD bash -c "airflow db init && \
    airflow users create --username admin --firstname Jose --lastname Pablo --role Admin --email example@email.org --password admin && \
    supervisord"
